#!/usr/bin/env python
#--/* libIntegra lua init script
#-- *  
#-- * Copyright (C) 2009 Kjetil Matheussen
#-- *
#-- * This program is free software; you can redistribute it and/or modify
#-- * it under the terms of the GNU General Public License as published by
#-- * the Free Software Foundation; either version 2 of the License, or
#-- * (at your option) any later version.
#-- *
#-- * This program is distributed in the hope that it will be useful,
#-- * but WITHOUT ANY WARRANTY; without even the implied warranty of
#-- * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#-- * GNU General Public License for more details.
#-- *
#-- * You should have received a copy of the GNU General Public License
#-- * along with this program; if not, write to the Free Software
#-- * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, 
#-- * USA.
#-- */

import sys,string

filename = sys.argv[1]
# assume our filename is of the form lua_<something>.lua
myname = filename[4:-4]
file=open(filename,"r")



sys.stdout.write('/* This file is autogenerated from %s. */\nstatic const char *ilua_%scode=\n' % (filename, myname));

while 1:
    line=file.readline()
    if line=="":
        sys.stdout.write(';\n')
        file.close()
        sys.exit(0)
    line=string.replace(line[:-1],'\\','\\\\')
    sys.stdout.write('"'+string.replace(line,'"','\\"')+'\\n"\n')
