---
definition:
    name:           Module
    label:          ~
    documentation:  ~
    core:           true
    instantiable:   FALSE
    parent:         Class
    description:    The base class for all Integra modules
attributes:
    - name:             active
      description:      Turns processing on and off
      scope:            public
      type:             integer
      unit:             ~
      scale:            ~
      minimum:          0
      maximum:          1
      default:          1
      legalvalues:      ~
      valuelabels:      {0: 'off', 1: 'on'}
      undoable:         true
      control:          ~
      controlattribute: ~
      controlgroup:     ~
...
