---
definition:
    name:           Processor
    label:          ~
    documentation:  ~
    core:           true
    instantiable:   FALSE
    parent:         Module
    description:    The base class for all processing modules
attributes:
    - name:             bypass
      description:      Bypasses the module processing
      scope:            public
      type:             integer
      unit:             ~
      scale:            ~
      minimum:          0
      maximum:          1
      default:          1
      undoable:         true
      legalvalues:      ~
      valuelabels:      {0: 'off', 1: 'on'}
      control:          ~
      controlattribute: ~
      controlgroup:     ~
    - name:             mute 
      description:      ~ 
      scope:            public
      type:             integer
      unit:             ~
      scale:            ~
      minimum:          0
      maximum:          1
      default:          1
      undoable:         true
      legalvalues:      ~
      valuelabels:      {0: 'off', 1: 'on'}
      control:          ~
      controlattribute: ~
      controlgroup:     ~
    - name:             inLevel
      description:      ~
      scope:            public
      type:             float
      unit:             ~
      scale:            ~
      minimum:          0.
      maximum:          1.
      default:          1.
      undoable:         true
      legalvalues:      ~
      valuelabels:      ~
      control:          ~
      controlattribute: ~
      controlgroup:     ~
    - name:             outLevel
      description:      ~
      scope:            public
      type:             float
      unit:             ~
      scale:            ~
      minimum:          0.
      maximum:          1.
      default:          1.
      undoable:         true
      legalvalues:      ~
      valuelabels:      ~
      control:          ~
      controlattribute: ~
      controlgroup:     ~
    - name:             mix
      description:      Controls the relative mix of processed/unprocessed sound
      scope:            public
      type:             float
      unit:             ~
      scale:            ~
      minimum:          0.
      maximum:          1.
      default:          1.
      undoable:         true
      legalvalues:      ~
      valuelabels:      ~
      control:          ~
      controlattribute: ~
      controlgroup:     ~
...
